version: '3.8'

services:

  frontend:
    image: y4r1k/dh-menu-frontend:latest
    ports:
      - "3000:3000"
    volumes:
      - frontend_build:/app/result_build/
    environment:
      NODE_ENV: production
    restart: always

  backend:
    image: y4r1k/dh-menu-backend:latest
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - static_value:/app/backend_static/
      - media_value:/app/backend_media/

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/dh-menu.crt:/etc/nginx/dh-menu.crt
      - ./nginx/dh-menu.key:/etc/nginx/dh-menu.key
      - frontend_build:/usr/share/nginx/html/
      - static_value:/var/html/backend_static/
      - media_value:/var/html/backend_media/
    restart: always
    depends_on:
      - backend
      - frontend

volumes:
  frontend_build:
  static_value:
  media_value:
