# Generated by Django 3.2 on 2023-10-20 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'ordering': ['pk'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='goodstype',
            options={'ordering': ['pk'], 'verbose_name': 'Тип меню', 'verbose_name_plural': 'Типы меню'},
        ),
    ]
