# Generated by Django 3.2 on 2023-10-20 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20231020_1502'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'ordering': ['title'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='goodssubtype',
            options={'ordering': ['pk'], 'verbose_name': 'Тип товара', 'verbose_name_plural': 'Типы товаров'},
        ),
        migrations.AlterModelOptions(
            name='hookahtobacco',
            options={'ordering': ['pk'], 'verbose_name': 'Тип табакаа', 'verbose_name_plural': 'Типы табаков'},
        ),
    ]
